version: '3.9'
services:
  db:
    image: postgres:16
    container_name: draftly_db
    environment:
      POSTGRES_USER: draftly
      POSTGRES_PASSWORD: draftly
      POSTGRES_DB: draftly
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: